/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-05-25 00:43:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#modDiv {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("\tmargin-left: -150px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tborder: 1px solid blue;\r\n");
      out.write("\tmargin: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li a {\r\n");
      out.write("\tmargin: 3px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id='modDiv' style=\"display: none;\">\r\n");
      out.write("\t\t<div class='modal-title'></div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type='text' id='replytext'>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"replyModBtn\">Modify</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"replyDelBtn\">DELETE</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id='closeBtn'>Close</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<h2>Ajax Test Page</h2>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\tREPLYER <input type='text' name='replyer' id='newReplyWriter'>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\tREPLY TEXT <input type='text' name='replytext' id='newReplyText'>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"replyAddBtn\">ADD REPLY</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<ul id=\"replies\">\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t<ul class='pagination'>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery 2.1.4 -->\r\n");
      out.write("\t<script src=\"/resources/plugins/jQuery/jQuery-2.1.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar bno = 106;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetPageList(1);\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getAllList() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.getJSON(\"/replies/all/\" + bno, function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data.length);\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(data).each(function() {\r\n");
      out.write("\t\t\t\t\tstr += \"<li data-rno='\"+this.rno+\"' class='replyLi'>\"+ this.rno+ \":\"\r\n");
      out.write("\t\t\t\t\t+ this.replytext + \"<button>MOD</button></li>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#replies\").html(str);\r\n");
      out.write("\t\t\t\tgetPageList(replyPage);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#replyAddBtn\").on(\"click\", function() {\r\n");
      out.write("\t\t\tvar replyer = $(\"#newReplyWriter\").val();\r\n");
      out.write("\t\t\tvar replytext = $(\"#newReplyText\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\turl : '/replies',\r\n");
      out.write("\t\t\t\theaders : {\r\n");
      out.write("\t\t\t\t\t\"Content-Type\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\t\"X-HTTP-Method-Override\" : \"POST\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tdata : JSON.stringify({\r\n");
      out.write("\t\t\t\t\tbno : bno,\r\n");
      out.write("\t\t\t\t\treplyer : replyer,\r\n");
      out.write("\t\t\t\t\treplytext : replytext\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tif (result == 'SUCCESS') {\r\n");
      out.write("\t\t\t\t\t\talert(\"등록 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tgetAllList();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#replies\").on(\"click\", \".replyLi button\", function() {\r\n");
      out.write("\t\t\tvar reply = $(this).parent();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar rno = reply.attr(\"data-rno\");\r\n");
      out.write("\t\t\tvar replytext = reply.text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".modal-title\").html(rno);\r\n");
      out.write("\t\t\t$(\"#replytext\").val(replytext);\r\n");
      out.write("\t\t\t$(\"#modDiv\").show(\"slow\");\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#replyDelBtn\").on(\"click\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar rno = $(\".modal-title\").html();\r\n");
      out.write("\t\t\tvar replytext = $(\"#replytext\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'delete',\r\n");
      out.write("\t\t\t\turl : '/replies/' + rno,\r\n");
      out.write("\t\t\t\theaders : {\r\n");
      out.write("\t\t\t\t\t\"Content-Type\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\t\"X-HTTP-Method-Override\" : \"DELETE\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result: \" + result);\r\n");
      out.write("\t\t\t\t\tif (result == 'SUCCESS') {\r\n");
      out.write("\t\t\t\t\t\talert(\"삭제 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("\t\t\t\t\t\tgetAllList();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#closeBtn\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#replyModBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  var rno = $(\".modal-title\").html();\r\n");
      out.write("\t\t\t  var replytext = $(\"#replytext\").val();\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'put',\r\n");
      out.write("\t\t\t\t\turl:'/replies/'+rno,\r\n");
      out.write("\t\t\t\t\theaders: { \r\n");
      out.write("\t\t\t\t\t      \"Content-Type\": \"application/json\",\r\n");
      out.write("\t\t\t\t\t      \"X-HTTP-Method-Override\": \"PUT\" },\r\n");
      out.write("\t\t\t\t\tdata:JSON.stringify({replytext:replytext}), \r\n");
      out.write("\t\t\t\t\tdataType:'text', \r\n");
      out.write("\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"result: \" + result);\r\n");
      out.write("\t\t\t\t\t\tif(result == 'SUCCESS'){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"수정 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t $(\"#modDiv\").hide(\"slow\");\r\n");
      out.write("\t\t\t\t\t\t\tgetAllList();\r\n");
      out.write("\t\t\t\t\t\t\t getPageList(replyPage);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}});\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getPageList(page){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  $.getJSON(\"/replies/\"+bno+\"/\"+page , function(data){\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  console.log(data.list.length);\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  var str =\"\";\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  $(data.list).each(function(){\r\n");
      out.write("\t\t\t\t  str+= \"<li data-rno='\"+this.rno+\"' class='replyLi'>\" \r\n");
      out.write("\t\t\t\t  +this.rno+\":\"+ this.replytext+\r\n");
      out.write("\t\t\t\t  \"<button>MOD</button></li>\";\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  $(\"#replies\").html(str);\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  printPaging(data.pageMaker);\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tfunction printPaging(pageMaker){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pageMaker.prev){\r\n");
      out.write("\t\t\t\tstr += \"<li><a href='\"+(pageMaker.startPage-1)+\"'> << </a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i=pageMaker.startPage, len = pageMaker.endPage; i <= len; i++){\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar strClass= pageMaker.cri.page == i?'class=active':'';\r\n");
      out.write("\t\t\t\t  str += \"<li \"+strClass+\"><a href='\"+i+\"'>\"+i+\"</a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pageMaker.next){\r\n");
      out.write("\t\t\t\tstr += \"<li><a href='\"+(pageMaker.endPage + 1)+\"'> >> </a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('.pagination').html(str);\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar replyPage = 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".pagination\").on(\"click\", \"li a\", function(event){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treplyPage = $(this).attr(\"href\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetPageList(replyPage);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
