/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2016-05-26 02:12:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class uploadAjax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("  \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".fileDrop {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tborder: 1px dotted blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("small {\r\n");
      out.write("\tmargin-left: 3px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h3>Ajax File Upload</h3>\r\n");
      out.write("\t<div class='fileDrop'></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class='uploadedList'></div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".fileDrop\").on(\"dragenter dragover\", function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".fileDrop\").on(\"drop\", function(event){\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar files = event.originalEvent.dataTransfer.files;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar file = files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\t//console.log(file);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar formData = new FormData();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tformData.append(\"file\", file);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t  url: '/uploadAjax',\r\n");
      out.write("\t\t\t\t  data: formData,\r\n");
      out.write("\t\t\t\t  dataType:'text',\r\n");
      out.write("\t\t\t\t  processData: false,\r\n");
      out.write("\t\t\t\t  contentType: false,\r\n");
      out.write("\t\t\t\t  type: 'POST',\r\n");
      out.write("\t\t\t\t  success: function(data){\r\n");
      out.write("\t\t\t\t\t  alert(data);\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  var str =\"\";\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  if(checkImageType(data)){\r\n");
      out.write("\t\t\t\t\t\t  str =\"<div><a href=displayFile?fileName=\"+getImageLink(data)+\">\"\r\n");
      out.write("\t\t\t\t\t\t\t\t  +\"<img src='displayFile?fileName=\"+data+\"'/>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t  +\"</a><small data-src=\"+data+\">X</small></div>\";\r\n");
      out.write("\t\t\t\t\t  }else{\r\n");
      out.write("\t\t\t\t\t\t  str = \"<div><a href='displayFile?fileName=\"+data+\"'>\" \r\n");
      out.write("\t\t\t\t\t\t\t\t  + getOriginalName(data)+\"</a>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t  +\"<small data-src=\"+data+\">X</small></div></div>\";\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  $(\".uploadedList\").append(str);\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t});\t \r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".uploadedList\").on(\"click\", \"small\", function(event){\r\n");
      out.write("\t\t\t\t var that = $(this);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t   url:\"deleteFile\",\r\n");
      out.write("\t\t\t\t   type:\"post\",\r\n");
      out.write("\t\t\t\t   data: {fileName:$(this).attr(\"data-src\")},\r\n");
      out.write("\t\t\t\t   dataType:\"text\",\r\n");
      out.write("\t\t\t\t   success:function(result){\r\n");
      out.write("\t\t\t\t\t   if(result == 'deleted'){\r\n");
      out.write("\t\t\talert(\"ddddddddddd\");\r\n");
      out.write("\t\t\t\t\t\t   that.parent(\"div\").remove();\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t   });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* \r\n");
      out.write("$(\".fileDrop\").on(\"drop\", function(event) {\r\n");
      out.write("\tevent.preventDefault();\r\n");
      out.write("\t\r\n");
      out.write("\tvar files = event.originalEvent.dataTransfer.files;\r\n");
      out.write("\t\r\n");
      out.write("\tvar file = files[0];\r\n");
      out.write("\r\n");
      out.write("\t//console.log(file);\r\n");
      out.write("\tvar formData = new FormData();\r\n");
      out.write("\t\r\n");
      out.write("\tformData.append(\"file\", file);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  url: '/uploadAjax',\r\n");
      out.write("\t\t  data: formData,\r\n");
      out.write("\t\t  dataType:'text',\r\n");
      out.write("\t\t  processData: false,\r\n");
      out.write("\t\t  contentType: false,\r\n");
      out.write("\t\t  type: 'POST',\r\n");
      out.write("\t\t  success: function(data){\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  var str =\"\";\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  console.log(data);\r\n");
      out.write("\t\t\t  console.log(checkImageType(data));\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  if(checkImageType(data)){\r\n");
      out.write("\t\t\t\t  str =\"<div><a href='displayFile?fileName=\"+getImageLink(data)+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t  +\"<img src='displayFile?fileName=\"+data+\"'/></a>\"\r\n");
      out.write("\t\t\t\t\t\t  +data +\"</div>\";\r\n");
      out.write("\t\t\t  }else{\r\n");
      out.write("\t\t\t\t  str = \"<div><a href='displayFile?fileName=\"+data+\"'>\" \r\n");
      out.write("\t\t\t\t\t\t  + getOriginalName(data)+\"</a></div>\";\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  $(\".uploadedList\").append(str);\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\t\t\t\r\n");
      out.write("});\t  */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getOriginalName(fileName){\t\r\n");
      out.write("\r\n");
      out.write("\tif(checkImageType(fileName)){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar idx = fileName.indexOf(\"_\") + 1 ;\r\n");
      out.write("\treturn fileName.substr(idx);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getImageLink(fileName){\r\n");
      out.write("\t\r\n");
      out.write("\tif(!checkImageType(fileName)){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar front = fileName.substr(0,12);\r\n");
      out.write("\tvar end = fileName.substr(14);\r\n");
      out.write("\t\r\n");
      out.write("\treturn front + end;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* \t\t$(\".fileDrop\").on(\"drop\", function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar files = event.originalEvent.dataTransfer.files;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar file = files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\t//console.log(file);\r\n");
      out.write("\t\t\tvar formData = new FormData();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tformData.append(\"file\", file);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t  url: '/uploadAjax',\r\n");
      out.write("\t\t\t\t  data: formData,\r\n");
      out.write("\t\t\t\t  dataType:'text',\r\n");
      out.write("\t\t\t\t  processData: false,\r\n");
      out.write("\t\t\t\t  contentType: false,\r\n");
      out.write("\t\t\t\t  type: 'POST',\r\n");
      out.write("\t\t\t\t  success: function(data){\r\n");
      out.write("\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t  alert(data);\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\tfunction checkImageType(fileName){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar pattern = /jpg|gif|png|jpeg/i;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn fileName.match(pattern);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
